apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jenkins-demo
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
